export const GET_MOVIES = 'GET_MOVIES'
export const SEARCH_MOVIES = 'SEARCH_MOVIES'
export const GET_MORE_MOVIES = "GET_MORE_MOVIES"
export const ERROR_RESET = "ERROR_RESET";
export const GET_MORE_SEARCH_MOVIES = "GET_MORE_SEARCH_MOVIES" 